import Head from 'next/head'
//styled components theme provider 
import { ThemeProvider } from 'styled-components'
//variables
import Theme from '../utilities/theme'
//global style
import GlobalStyle from '../utilities/style/Global'
// add bootstrap css 
import 'bootstrap/dist/css/bootstrap.css'
import Main from './home'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <ThemeProvider theme={Theme}>
        <GlobalStyle />
        <Main />
      </ThemeProvider>
    </div>
  )
}
